In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import log_loss, accuracy_score

In [3]:
df = pd.read_excel('data_1_final.xlsx')

In [272]:
df.head()

Sr No  Quote Id           Make           Model             Variant  \
0    251    300647           TATA  INDICA V2 XETA             1.4 GLS   
1    252    300646         MARUTI            EECO  5 STR WITH A/C+HTR   
2    253    300645      CHEVROLET           SPARK              1.0 LT   
3    254    300644  NISSAN MOTORS         X-TRAIL                  LE   
4    255    300643        HYUNDAI             EON            ERA PLUS   

                   RTO State                  RTO City            Agent Name  \
0                      Delhi  SOUTH DELHI-SHEIKH SARAI  Mohammed Hafeez khan   
1                     Kerala        THIRUVANANTHAPURAM            Neha Khare   
2                      Assam                    KAMRUP    Kireeti Pasupuleti   
3            Jammu & Kashmir                     JAMMU           Pardeep Pal   
4  Andaman & Nicobar Islands                PORT BLAIR  Venkatesh Upperpally   

  call picked by customer  Calls attempted by agent  calls made by cust  \
0                     Yes                         5                   0   
1                      No                         0                   0   
2                      No                         1                   0   
3                     Yes                         4                   0   
4                     Yes                         1                   0   

   Connected Calls       Agent tone  total calls durationæ Asked to call back  \
0                1             Good                    265                 No   
1                0  Call Not Picked                      0    Call Not Picked   
2                0  Call Not Picked                      0    Call Not Picked   
3                3             Good                    107                Yes   
4                1             Good                    255                Yes   

  Customer Interest  Days to expire Expiry status Purchased  
0        Interested               2     Days_left        No  
1    Not Interested               0       No_data        No  
2    Not Interested               0       No_data        No  
3    Not Interested               0       No_data        No  
4        Interested               0       Expired        No

In [273]:
df1=df.drop(['Sr No','Quote Id'], axis=1)

In [274]:
df1.head()

Make           Model             Variant  \
0           TATA  INDICA V2 XETA             1.4 GLS   
1         MARUTI            EECO  5 STR WITH A/C+HTR   
2      CHEVROLET           SPARK              1.0 LT   
3  NISSAN MOTORS         X-TRAIL                  LE   
4        HYUNDAI             EON            ERA PLUS   

                   RTO State                  RTO City            Agent Name  \
0                      Delhi  SOUTH DELHI-SHEIKH SARAI  Mohammed Hafeez khan   
1                     Kerala        THIRUVANANTHAPURAM            Neha Khare   
2                      Assam                    KAMRUP    Kireeti Pasupuleti   
3            Jammu & Kashmir                     JAMMU           Pardeep Pal   
4  Andaman & Nicobar Islands                PORT BLAIR  Venkatesh Upperpally   

  call picked by customer  Calls attempted by agent  calls made by cust  \
0                     Yes                         5                   0   
1                      No                         0                   0   
2                      No                         1                   0   
3                     Yes                         4                   0   
4                     Yes                         1                   0   

   Connected Calls       Agent tone  total calls durationæ Asked to call back  \
0                1             Good                    265                 No   
1                0  Call Not Picked                      0    Call Not Picked   
2                0  Call Not Picked                      0    Call Not Picked   
3                3             Good                    107                Yes   
4                1             Good                    255                Yes   

  Customer Interest  Days to expire Expiry status Purchased  
0        Interested               2     Days_left        No  
1    Not Interested               0       No_data        No  
2    Not Interested               0       No_data        No  
3    Not Interested               0       No_data        No  
4        Interested               0       Expired        No

In [275]:
null_columns=df1.columns[df1.isnull().any()]
df1[null_columns].isnull().sum()


Series([], dtype: float64)

In [276]:
df1=df1.iloc[:,5:]

In [277]:
df1.dtypes

Agent Name                  object
call picked by customer     object
Calls attempted by agent     int64
calls made by cust           int64
Connected Calls              int64
Agent tone                  object
total calls durationæ        int64
Asked to call back          object
Customer Interest           object
Days to expire               int64
Expiry status               object
Purchased                   object
dtype: object

In [278]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for i in df1.columns:
    if df1[i].dtype == object:
        df1[i] = le.fit_transform(df1[i])
    else:
        pass

In [279]:
df1.head()

Agent Name  call picked by customer  Calls attempted by agent  \
0           8                        1                         5   
1          12                        0                         0   
2           5                        0                         1   
3          13                        1                         4   
4          22                        1                         1   

   calls made by cust  Connected Calls  Agent tone  total calls durationæ  \
0                   0                1           2                    265   
1                   0                0           1                      0   
2                   0                0           1                      0   
3                   0                3           2                    107   
4                   0                1           2                    255   

   Asked to call back  Customer Interest  Days to expire  Expiry status  \
0                   1                  0               2              0   
1                   0                  2               0              3   
2                   0                  2               0              3   
3                   2                  2               0              3   
4                   2                  0               0              1   

   Purchased  
0          0  
1          0  
2          0  
3          0  
4          0

In [280]:
from sklearn.model_selection import train_test_split
X = df1.drop('Purchased',axis='columns')
y = df1.Purchased

In [452]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.099, random_state=20)
X_train.head()

Agent Name  call picked by customer  Calls attempted by agent  \
60          19                        1                         2   
94          14                        1                         5   
35           3                        1                        11   
89           7                        1                        14   
5           22                        1                         3   

    calls made by cust  Connected Calls  Agent tone  total calls durationæ  \
60                   0                2           2                   1929   
94                   0                3           2                    692   
35                   0                1           2                    160   
89                   1               10           2                   3214   
5                    0                1           2                     34   

    Asked to call back  Customer Interest  Days to expire  Expiry status  
60                   1                  0               0              2  
94                   1                  0              20              0  
35                   1                  2               0              3  
89                   2                  0               0              1  
5                    1                  2               0              3

In [453]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1208, random_state=20)
X_train.head()

Agent Name  call picked by customer  Calls attempted by agent  \
13          19                        0                         1   
22          13                        1                         1   
60          19                        1                         2   
91           5                        1                        13   
63          19                        1                         2   

    calls made by cust  Connected Calls  Agent tone  total calls durationæ  \
13                   0                0           1                      0   
22                   0                1           2                     41   
60                   0                2           2                   1929   
91                   0                8           2                   2630   
63                   0                2           2                   2024   

    Asked to call back  Customer Interest  Days to expire  Expiry status  
13                   0                  2               0              3  
22                   1                  0               0              3  
60                   1                  0               0              2  
91                   1                  0               7              0  
63                   1                  0              12              0

In [454]:
len(X_val)

11

In [455]:
#Import Library
model = SVC(kernel='linear', random_state=1)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=1, shrinking=True,
  tol=0.001, verbose=False)

In [456]:
predicted=model.predict(X_val)

In [457]:
cm = confusion_matrix(y_val, predicted)
print(cm)

[[3 0]
 [1 7]]


In [458]:
accuracy_score(y_val,predicted)

0.9090909090909091

In [459]:
p=model.predict(X_test)

In [460]:
cm = confusion_matrix(y_test, p)
print(cm)

[[8 1]
 [0 1]]


In [461]:
accuracy_score(y_test,p)

0.9

In [462]:
classifier_entropy = DecisionTreeClassifier(criterion='entropy', random_state=1)
classifier_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')

In [463]:
y_pred_ent_val = classifier_entropy.predict(X_val)

In [464]:
cm = confusion_matrix(y_val, y_pred_ent_val)
print(cm)

[[3 0]
 [5 3]]


In [465]:
accuracy_score(y_val,y_pred_ent_val)

0.5454545454545454

In [ ]:
y_pred_ent = classifier_entropy.predict(X_test)

In [467]:
cm = confusion_matrix(y_test, y_pred_ent)
print(cm)

[[6 3]
 [0 1]]


In [468]:
accuracy_score(y_test,y_pred_ent)

0.7

In [485]:
seed = 100
grad_boost=GradientBoostingClassifier(
    max_depth = 70,
    n_estimators = 1000,
    warm_start=True,
    random_state = 1 )

grad_boost.fit(X_train, y_train)

grad_boost_pred_val=grad_boost.predict(X_val)
grad_boost_pred_prob_val=grad_boost.predict_proba(X_val)

grad_boost_acc_val=accuracy_score(y_val, grad_boost_pred_val)
grad_boost_loss_val=log_loss(y_val,grad_boost_pred_prob_val)

print(" Gradient Boost Classifier")

print("Accuracy: {0: .2f}".format(grad_boost_acc_val))
print("Logaritmic Loss: {0: .2f}".format(grad_boost_loss_val))

 Gradient Boost Classifier
Accuracy:  0.55
Logaritmic Loss:  3.07


In [486]:
grad_boost_pred=grad_boost.predict(X_test)
grad_boost_pred_prob=grad_boost.predict_proba(X_test)

grad_boost_acc=accuracy_score(y_test, grad_boost_pred)
grad_boost_loss=log_loss(y_test,grad_boost_pred_prob)

print(" Gradient Boost Classifier")

print("Accuracy: {0: .2f}".format(grad_boost_acc))
print("Logaritmic Loss: {0: .2f}".format(grad_boost_loss))
#print("number of nodes created in decision tree: {0: .2f}".format(dec_tree.tree_.node_count))

 Gradient Boost Classifier
Accuracy:  0.80
Logaritmic Loss:  0.19
